version: 2.1

# 定义执行器配置
executors:
  docker-executor:
    docker:
      - image: pandaman666/ubuntu:custom-xict-devel-ubuntu20.04-tensorrt8.5.3.1
    environment:  # 设置全局环境变量
      CCACHE_DIR: /tmp/.ccache  # 缓存目录

# 定义工作流
workflows:
  build_and_test:  # 工作流名称
    jobs:  # 工作流包含的作业
      - build  # 构建作业
      - test:
          requires:
            - build

# 作业定义
jobs:
  build:  # 构建作业
    executor: docker-executor
    resource_class: large
    steps:
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts  # 配置SSH
      - run:
          name: Checkout
          command: git clone -b main git@github.com:Y-pandaman/env-docker.git
      - restore_cache:  # 恢复缓存步骤
          keys:
            - docker-ccache
      - run:
          name: Install docker
          command: |
            apt-get update && apt-get install ca-certificates curl && install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update
            apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
            systemctl daemon-reload && systemctl restart docker
      - run:
          name: build docker  images
          command: |
            for((i=1;i<=500;i++)); do docker pull pandaman666/ubuntu:vanilla-base-ubuntu18.04; docker rmi pandaman666/ubuntu:vanilla-base-ubuntu18.04; echo $i; done
            cd env-docker && ./build.sh --package-name custom --package-version xict  --os ubuntu --os-version 20.04 --arch amd64,arm64 --num-threads 4 --push --image-suffix tensorrt8.5.3.1 --extra-args "--build-arg BASE_PACKAGE=tensorrt-8.5.3.1"
      - save_cache:  # 保存缓存步骤
          key: docker-ccache
          paths:
            - /tmp/.ccache
      - persist_to_workspace:  # 持久化到工作空间步骤
          root: .
          paths:
            - .
  test:
    executor: docker-executor
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test docker images
          command: |
            echo "test docker images"